<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PianoMapper.Core\PianoMapper.Core.csproj" />
        <ProjectReference Include="..\PianoMapper.Web\PianoMapper.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PianoMapper.Tests" />
    </ItemGroup>

</Project>
